# Generated by Django 5.1.1 on 2024-09-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_manufactured_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_contact",
                    models.CharField(
                        help_text="Введите тип контактных данных",
                        max_length=100,
                        verbose_name="Тип контактных данных",
                    ),
                ),
                (
                    "value_contact",
                    models.CharField(
                        help_text="Введите значение контактных данных",
                        max_length=150,
                        verbose_name="Значение контактных данных",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контактные данные",
                "verbose_name_plural": "Контактные данные",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория продукта",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="manufactured_at",
        ),
    ]
